using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerAttackHitBox : MonoBehaviour
{
    // Attack and animation is still playing
    public bool attackActive;

    // Attack damage and knockback force on the X and Y axes.
    private float attackDamage;
    private float attackHorizontalForce;
    private float attackVerticalForce;
    
    // Size of the hitbox generated by the attack.
    private Vector2 attackHitBoxSize;

    // Time in seconds to fully perform the attack.
    private float duration;

    private BoxCollider hitBox;

    private void Start()
    {
        hitBox = gameObject.GetComponent<BoxCollider>();
        
        // Deactivate attack also can serve to initialize all the variables to standard values.
        DeactivateAttack();
    }

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            PrepareNextAttack(50, 10, 10, new Vector3(0.33f, 0.33f, 0.33f), 0.5f);
        }
        
        if (!attackActive) { return; }
        
        duration -= Time.deltaTime;
        if (duration <= 0f)
        {
            attackActive = false;
            DeactivateAttack();
        }
    }
    
    public void PrepareNextAttack(float _damage, float _Hforce, float _Vforce, Vector3 _size, float _duration)
    {
        attackDamage = _damage;
        
        attackHorizontalForce = _Hforce;
        attackVerticalForce = _Vforce;

        duration = _duration;

        attackActive = true;
        attackHitBoxSize = _size;

        hitBox.enabled = true;
        hitBox.size = attackHitBoxSize;

        // TEMPORARY TO VISUALIZE HITBOX SIZES - Remove later!
        gameObject.transform.localScale = _size;
    }

    private void DeactivateAttack()
    {
        attackDamage = 0;
        
        attackHorizontalForce = 0;
        attackVerticalForce = 0;
        
        duration = 0;
        
        attackActive = false;
        hitBox.size = Vector2.zero;
        hitBox.enabled = false;

        // TEMPORARY TO VISUALIZE HITBOX SIZES - Remove later!
        gameObject.transform.localScale = Vector3.zero;
    }

    private void OnTriggerEnter(Collider other)
    {
        Debug.Log($"Current: {gameObject.name}. Other: {other.gameObject.name}.");

        if (other.transform != transform.parent && other.transform.CompareTag("Player"))
        {
            DeactivateAttack();
            // Other.TakeDamage();
            // Other.Knockback();

            // Direction is from the parent of the hitbox (which is the attacking player) to the other player.
            Vector3 normalizedDirection = Vector3.Normalize(other.transform.position - transform.parent.position);

            Debug.DrawRay(transform.position, normalizedDirection * 5f, Color.red, 5f);

            other.gameObject.GetComponent<Rigidbody>().AddForce(normalizedDirection * 50f, ForceMode.Impulse);
        }
    }
}
